export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILE = 'LOGIN_FAILE';
export const LOGIN = 'LOGIN';
export const REGISTURE = 'REGISTURE';
export const REGISTURE_SUCCESS = 'REGISTURE_SUCCESS';
export const REGISTURE_FAILE = 'REGISTURE_FAILE';
